version: '3.8'

networks:
  web:
    external: true
  internal:
    external: false

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: recipe-app
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY_ID=uS4yfmTlVP1rBakV1T45
      - MINIO_SECRET_ACCESS_KEY=peOlGbNFAAP2Rcr4DvfPijgB1FKEkBMynURpOZEU
      - MONGO_ENDPOINT=mongodb://mongodb:27017
      - REDIS_ENDPOINT=redis:6379
      - CALLBACK_ADDRESS=https://recipe.ferber.io/callback
      - CASDOOR_ENDPOINT=https://auth.ferber.io
      - APP_ADDR=https://recipe.ferber.io
    depends_on:
      - minio
      - mongodb
      - redis
    networks:
      - internal
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recipe.rule=Host(`recipe.ferber.io`)"
      - "traefik.http.routers.recipe.entrypoints=web,websecure"
      - "traefik.http.services.recipe-service.loadbalancer.server.port=3000"
      - "traefik.http.routers.recipe.service=recipe-service"
      - "traefik.http.routers.recipe.tls=true"
      - "traefik.http.routers.recipe.tls.certresolver=lets-encrypt"


  minio:
    image: quay.io/minio/minio
    container_name: miniocontainer
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=uS4yfmTlVP1rBakV1T45
      - MINIO_ROOT_PASSWORD=peOlGbNFAAP2Rcr4DvfPijgB1FKEkBMynURpOZEU
    command: server /data --console-address ":9001"
    networks:
      - internal
      - web
    volumes:
      - minio-data:/data
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - internal
      - web
    volumes:
      - redis-data:/data
    restart: unless-stopped

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - internal
      - web
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  minio-data:
  redis-data:
  mongo-data: